# Generated by Django 4.2.5 on 2023-12-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0002_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering')], default='None', max_length=30),
        ),
    ]
