# Generated by Django 4.2.5 on 2023-12-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0006_remove_ticket_student_ticket_nuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nuid',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
