# Generated by Django 4.2.5 on 2023-12-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0007_alter_ticket_nuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='nuid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(default=3300, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Onestop_App.student'),
            preserve_default=False,
        ),
    ]
