# Generated by Django 4.2.5 on 2023-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0008_remove_ticket_nuid_ticket_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(choices=[('course_withdrawal', 'Course Withdrawal'), ('change_section', 'Change Section'), ('change_course', 'Change Course'), ('tuition_fees', 'Tuition Fees')], default='None', max_length=30),
        ),
    ]
