# Generated by Django 4.2.5 on 2023-12-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0009_alter_ticket_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
