# Generated by Django 4.2.5 on 2023-12-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
