# Generated by Django 4.2.5 on 2023-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0011_remove_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
