# Generated by Django 4.2.5 on 2023-12-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onestop_App', '0013_notification_ticket_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('scheduled', 'Scheduled'), ('complete', 'Complete')], default='submitted', max_length=20),
        ),
    ]
