from django.urls import path
from . import views
from .customDecorator import admin_required, anonymous_required, normal_user_required
from django.contrib.auth.decorators import login_required

app_name = "Onestop_App"
urlpatterns = [
    path(
        "",
        views.student_login,
        name="student_login"
    ),
    path(
        "create_query/",
        login_required(views.create_query),
        name="create_query"
    ),
    path(
        "query_status/",
        login_required(views.query_status),
        name="query_status"
    ),
    path(
        "student_timetabe/",
        login_required(views.student_timetable),
        name="student_timetable",
    ),
    path(
        "student_dashboard/",
        login_required(views.student_dashboard),
        name="student_dashboard",
    ),
    path(
        "student_logout/",
        login_required(views.student_logout),
        name="student_logout",
    ),
    path(
        "admin_dashboard/",
        admin_required(views.dashboard),
        name="dashboard"
    ),
    path(
        "admin_login/",
        anonymous_required(views.admin_login),
        name="admin_login",
    ),
    path(
        "admin_logout/",
        admin_required(views.admin_logout),
        name="admin_logout",
    ),
    path(
        "add_student/",
        admin_required(views.add_student),
        name="add_student",
    ),
    path(
        "add_faculty/",
        admin_required(views.add_faculty),
        name="add_faculty",
    ),
    path(
        "add_course/",
        admin_required(views.add_course),
        name="add_course",
    ),
    path(
        "add_section/",
        admin_required(views.add_section),
        name="add_section",
    ),
    path(
        "admin_queries/",
        admin_required(views.admin_queries),
        name="admin_queries",
    ),
    path(
        "admin_response/<int:ticket_id>/",
        admin_required(views.admin_response),
        name="admin_response",
    ),
    path(
        "chatbot/",
        login_required(views.chatbot_view),
        name="chatbot"
    ),
    path(
        "admin_notifications/",
        admin_required(views.admin_notifications),
        name="admin_notifications"
    ),
    path(
        'mark_notification_as_read/<int:notification_id>/',
        admin_required(views.mark_notification_as_read),
        name='mark_notification_as_read'
    ),
    path(
        'ticket_detail/<int:ticket_id>/',
        admin_required(views.ticket_detail), 
        name='ticket_detail'
    ),
    path(
        "student_notifications/",
        login_required(views.user_notifications),
        name="student_notifications",
    ),
    path(
        'ticket_det/<int:ticket_id>/',
        login_required(views.ticket_det),
        name='ticket_det',
    ),
    path(
        'schedule_appointment/',
        login_required(views.schedule_appointment),
        name='schedule_appointment',
    ),
    path(
        'change_appointment_status/<int:appointment_id>/', 
        admin_required(views.change_appointment_status), 
        name='change_appointment_status'
    ),
    path(
        'all_appointments/', 
        admin_required(views.all_appointments), 
        name='all_appointments'
    ),
    path(
        'appointment_detail/<int:appointment_id>/', 
        admin_required(views.appointment_detail), 
        name='appointment_detail'
    ),
]
